# Site settings
author: Maddy
title: just a little blog
header-img: img/home-bg.png
email: reiser.mb@gmail.com
copyright_name: Maddy
description: > # this means to ignore newlines until "baseurl:"
  my journey in becoming a data scientist
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  turtleduck18

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
